### ISSUE TITLE
Release a new version tthat supports the latest Faraday

### ISSUE THREAD

**Issue by kou** [sckott/veyor#7]
Do you have any plan to release a new version that includes https://github.com/sckott/veyor/commit/d623bd2b07086b37837bf42befdd158dbf670113?

**Comment by sckott** [comment]
yes, been planning to, will make it happen soon

**Comment by kou** [comment]
Thanks!

**Comment by kou** [comment]
Are there any blockers?
It seems that you've tried to release a new version https://github.com/sckott/veyor/commit/dfd35a072b8650311853447cba92bc54d7bd07b7 but new version isn't released yet: https://rubygems.org/gems/veyor/

**Comment by sckott** [comment]
releasing today

**Comment by sckott** [comment]
@kou its up now https://rubygems.org/gems/veyor

**Comment by kou** [comment]
Thanks!!!
